feat: implement rht_pq_map
yorkie-team/yorkie-rust-sdk pull request #16
Opened 2022-02-23 14:50 UTC by blurfx

### What this PR does / why we need it?

### What are the relevant tickets?

Fixes #9

### Any background context you want to provide?

### Checklist
- [x] Added relevant tests or not required
- [x] Didn't break anything

2022-02-23 14:50 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/signed)](https://cla-assistant.io/yorkie-team/yorkie-rust-sdk?pullRequest=16) <br/>All committers have signed the CLA.

2022-02-26 10:25 UTC, dc7303 requested changes
Thank you for the great work! I left a few comments, so please check them out.

2022-02-26 10:25 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +    node_map_by_created_at: HashMap<String, RHTPQMapNode>,
```suggestion
    node_map_by_created_at: HashMap<Ticket, RHTPQMapNode>,
```

In https://github.com/yorkie-team/yorkie-rust-sdk/pull/12, we made the Ticket usable as a hashmap key. I think it would be better to use Ticket as the key type instead of String, what do you think?

2022-02-26 10:25 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +    fn set_internal(&mut self, key: String, value: BoxedElement) {
It looks like it should be called from the set method.

2022-02-26 10:25 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +            .node_queue_map_by_key
It appears that each hashmap key is being used in reverse. is that intended?

2022-02-26 10:25 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +                    false => Some(&node.element),
It seems like the correct behavior to return None when false and return an element when the deletion is successful. Do you have any other intentions?

2022-02-26 10:25 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +                    Some(node.element.clone())
It seems like the correct behavior to return None when false and return an element when the deletion is successful. Do you have any other intentions?

2022-02-26 10:25 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +    ) -> Option<BoxedElement> {
The `delete` method above returns a reference to the Element. And this method returns the cloned Element. I'm curious about the difference between these two. Could you please explain?

2022-02-26 10:34 UTC, hackerwins reviewed
Thanks for your contribution.

1. I'm a beginner in Rust now and there is a pattern I'm not familiar with. Please explain the part I commented on. I think @dc7303  and I can learn something new.
2. How about implementing this with test codes?

2022-02-26 10:34 UTC, hackerwins commented on src/document/json/element.rs
> +    fn created_at(&self) -> Ticket;
We have been following the getters naming convention of using `XXX` instead of `GetXXX` in Go.
https://go.dev/doc/effective_go#Getters

Is there a naming convention for getters in Rust?

```suggestion
    fn created_at(&self) -> Ticket;
```

2022-02-26 10:34 UTC, hackerwins commented on src/document/json/rht_pq_map.rs
> +impl Eq for RHTPQMapNode {}
I think the functions implemented in `impl XXX for RHTPQMapNode` are used in BinaryHeap. Is it ok to empty the implementation of Eq?

2022-02-26 10:34 UTC, hackerwins commented on src/document/json/rht_pq_map.rs
> +}
RHT uses the pair of RC and RefCell(`HashMap<String, RC<RefCell<XXX>>>`) when different containers own the same instance. I think it's handled in a different way here, what are the pros and cons?

https://github.com/yorkie-team/yorkie-rust-sdk/blob/eaefcf4d55d1ba2c890fd279b7aec1f7fea1009f/src/document/json/rht.rs#L69-L72

2022-02-26 10:34 UTC, hackerwins commented on src/document/json/rht_pq_map.rs
> +}
@dc7303 Looks like a way to define custom errors has been introduced. We may need to apply this to other codes as well.

2022-02-26 10:36 UTC, blurfx commented on src/document/json/rht_pq_map.rs
> +    fn set_internal(&mut self, key: String, value: BoxedElement) {
wait. didn't I do that?

2022-02-26 10:36 UTC, blurfx commented on src/document/json/rht_pq_map.rs
> +    fn set_internal(&mut self, key: String, value: BoxedElement) {
oh

2022-02-26 10:36 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +}
That seems like a good idea. :)

2022-02-26 10:50 UTC, blurfx commented on src/document/json/rht_pq_map.rs
> +impl Eq for RHTPQMapNode {}
As far as I know BinaryHeap uses `Ord` to sort nodes, and `Ord` depends on `PartialEq`. But what I know may be outdated or wrong. Can I see a reference for the part?

2022-02-26 10:54 UTC, blurfx commented on src/document/json/rht_pq_map.rs
> +}
There are not many contexts I understand about yorkie core implementation, so I wrote them in such a general way.
If those values require multiple ownership, I think it's right to use `Rc` and `RefCell`.

2022-02-26 10:59 UTC, blurfx commented on src/document/json/rht_pq_map.rs
> +            .node_queue_map_by_key
No. It's my mistake.

2022-02-26 11:14 UTC, blurfx commented on src/document/json/rht_pq_map.rs
> +}
(cc @dc7303 )

2022-02-26 11:19 UTC, blurfx commented on src/document/json/rht_pq_map.rs
> +    ) -> Option<BoxedElement> {
I think it's right to return the cloned element not reference.

Most of the parts you pointed out in this review were written almost a month ago, and I don't remember why I wrote it like that. (maybe I was drunk)

2022-02-26 12:08 UTC, hackerwins commented on src/document/json/element.rs
> +    fn created_at(&self) -> Ticket;
https://rust-lang.github.io/api-guidelines/naming.html#getter-names-follow-rust-convention-c-getter

2022-02-26 12:59 UTC, blurfx commented on src/document/json/rht_pq_map.rs
> +    ) -> Option<BoxedElement> {
Return type of `delete` method has changed on this [commit](
https://github.com/yorkie-team/yorkie-rust-sdk/pull/16/commits/87db154500838c247a4836a94b1f1ac6cf28ced4#diff-3754be579edd1141aea09893bf062ade8d44b469ec178d36d28d0419e518cdc6R149)

2022-04-07 12:53 UTC, hackerwins approved these changes
Thanks for your contribution.
(Sorry for the late)

2022-04-07 15:53 UTC, dc7303 requested changes
Sorry for the late review. 🙏 

## About Test Code
Using smart pointers in Rust can cause errors at runtime. Also, since this data structure deals with an abstract element called Element, it is easy to make mistakes in concrete implementation.
So I think we need some test code for the step now.
(Most of the changes I suggest are issues I discovered while writing the test code.)

So, I wrote a test. And in the case of the actual `set()` method, it was confirmed that the intended operation was not performed.
```
failures:

---- document::json::rht_pq_map::tests::data_handle stdout ----
thread 'document::json::rht_pq_map::tests::data_handle' panicked at 'assertion failed: false', src/document/json/rht_pq_map.rs:387:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

How about improving the codes along with the tests based on this test code?

- The MockElement in the test code shared below may seem overdone. If an element such as Primitive is added, MockElement will be replaced with Primitive.


### my test code:
```rust
#[cfg(test)]
mod tests {
    use super::*;
    use crate::document::time::ticket::Ticket;
    use crate::document::json::element::Element;
    use crate::document::time::actor_id::ActorID;

    struct MockElement {
        value: u32,
        created_at: Ticket,
        moved_at: Option<Ticket>,
        removed_at: Option<Ticket>,
    }

    impl MockElement {
        fn new(value: u32, created_at: Ticket) -> MockElement {
            return MockElement {
                value,
                created_at,
                moved_at: None,
                removed_at: None,
            }
        }
    }

    impl Element for MockElement {
        fn to_string(&self) -> String {
            self.value.to_string()
        }

        fn deepcopy(&self) -> Box<dyn Element> {
            let moved_at = match &self.moved_at {
                Some(moved_at) => Some(moved_at.clone()),
                _ => None,
            };

            let removed_at = match &self.removed_at {
                Some(removed_at) => Some(removed_at.clone()),
                _ => None,
            };

            let element = MockElement {
                value: self.value,
                created_at: self.created_at.clone(),
                moved_at: moved_at,
                removed_at: removed_at,
            };

            Box::new(element)
        }

        fn created_at(&self) -> Ticket {
            self.created_at.clone()
        }

        fn moved_at(&self) -> Option<Ticket> {
            if let Some(moved_at) = &self.moved_at {
                return Some(moved_at.clone());
            }

            None
        }

        fn set_moved_at(&mut self, ticket: Ticket) {
            self.moved_at = Some(ticket);
        }

        fn removed_at(&self) -> Option<Ticket> {
            if let Some(removed_at) = &self.removed_at {
                return Some(removed_at.clone());
            }

            None
        }

        fn remove(&mut self, ticket: Ticket) -> bool {
            if ticket.after(&self.created_at) {
                match &self.removed_at {
                    Some(removed_at) => {
                        if ticket.after(removed_at) {
                            self.removed_at = Some(ticket);
                            return true;
                        }
                    },
                    _ => {
                        self.removed_at = Some(ticket);
                        return true;
                    }
                }
            }

            false
        }
    }

    #[test]
    fn data_handle() {
        let mut map = RHTPriorityQueueMap::new();
        let hex_str = "0123456789abcdef01234567";
        let actor_id = ActorID::from_hex(hex_str).unwrap();
        let created_at = Ticket::new(0, 0, actor_id);

        // set
        let result = map.set("data".to_string(), Box::new(MockElement::new(1, created_at.clone())));
        if let Some(_) = result {
            assert!(false);
        };

        let result = map.set("data".to_string(), Box::new(MockElement::new(2, created_at.clone())));
        match result {
            Some(element) => assert_eq!(element.to_string(), "2"),
            _ => assert!(false),
        }
    }
}
```

## About generic
The current code is using the Box smart pointer. If you use generics, I think you can make your code look better by not using Box. What do you think?

2022-04-07 15:53 UTC, dc7303 commented on src/document/json/element.rs
> +    fn remove(&self, ticket: Ticket) -> bool;
```suggestion
    fn remove(&mut self, ticket: Ticket) -> bool;
```

2022-04-07 15:53 UTC, dc7303 commented on src/document/json/element.rs
> +    fn set_moved_at(&self, ticket: Ticket);
```suggestion
    fn set_moved_at(&mut self, ticket: Ticket);
```

2022-04-07 15:53 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +                let node = node.borrow();
```suggestion
                let mut node = node.borrow_mut();
```

2022-04-07 15:53 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +    pub fn set_internal(&mut self, key: String, value: BoxedElement) {
```suggestion
    fn set_internal(&mut self, key: String, value: BoxedElement) {
```
This method seems like the private method.

2022-04-07 15:53 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +                    let node = node.borrow();
```suggestion
                    let mut node = node.borrow_mut();
```

2022-04-07 15:53 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +            let node = node.borrow();
```suggestion
            let mut node = node.borrow_mut();
```

2022-04-07 15:53 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +                        node.remove(node.element.created_at());
```suggestion
                        let created_at = node.element.created_at();
                        node.remove(created_at);
```

2022-04-07 15:53 UTC, dc7303 commented on src/document/json/rht_pq_map.rs
> +}
```suggestion
struct RHTPQMapNode<E: Element> {
    key: String,
    element: E,
}
```
How about using generic?
If using generic then not need to Box.

2022-04-20 12:37 UTC, blurfx commented on src/document/json/rht_pq_map.rs
> +}
I didn't know that. Thank you!

2022-04-25 05:08 UTC, hackerwins approved these changes

2022-04-25 15:25 UTC, dc7303 requested changes
Thank you for taking my comments into account 🙇 

Now that we are ready to test, we can extend our tests. How about extending your tests to test other public methods?

It's also good to add a test case. We need to check that the currently implemented public methods work well.

For example, you can test the has() and delete() methods.
I tested the has() and delete() methods and found that it didn't work as we intended. Below I attach the test code that I have extended.


```rust
    #[test]
    fn data_handle() {
        .......
        // set return removed element
        let created_at = Ticket::new(0, 1, actor_id.clone());
        let result = map.set("data".to_string(), MockElement::new(2, created_at));
        match result {
            Some(element) => assert_eq!(element.to_string(), "1"),
            _ => assert!(false),
        }
                
        // has data
        assert!(map.has("data"));

        // delete
        let deleted_at = Ticket::new(0, 2, actor_id.clone());
        match map.delete("data".to_string(), deleted_at) {
            Some(element) => assert_eq!(element.to_string(), "2"),
            _ => assert!(false),
        }
    }
```
### has() Fail log
```bash
failures:

---- document::json::rht_pq_map::rht_pq_map_tests::data_handle stdout ----
thread 'document::json::rht_pq_map::rht_pq_map_tests::data_handle' panicked at 'assertion failed: map.has(\"data\")', src/document/json/rht_pq_map.rs:386:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### delete() Fail log
```bash
failures:

---- document::json::rht_pq_map::rht_pq_map_tests::data_handle stdout ----
thread 'document::json::rht_pq_map::rht_pq_map_tests::data_handle' panicked at 'assertion failed: `(left == right)`
  left: `"1"`,
 right: `"2"`', src/document/json/rht_pq_map.rs:391:30
```

2024-09-10 00:57 UTC, closed without merging